### ISSUE TITLE
Incompatibility with DirectAdmin

### ISSUE THREAD

**Issue by paulonichio** [The-Network-Crew/CSF-Unblocker-for-WHMCS#1]
Hello,

I've installed the module on my WHMCS 8.8.0 (PHP 7.4.33), but the integration with DirectAdmin isn't working. Upon checking the error logs, we identified the following entry:

`curl_exec threw error "Failed sending HTTP request" for https://IP_SERVER:2222/CMD_PLUGINS_ADMIN/csf/index.html?action=grep&ip=8.8.8.8, referer: https://My_WHMCS.com/index.php?m=unblockip`

Could you please confirm if the module is compatible with DirectAdmin?

Thank you.

**Comment by lsthompson** [comment]
At this time, we're not able to confirm functionality with DA, so have removed the mention from the README! Apologies.
