### ISSUE TITLE
Nothing happen in client area

### ISSUE THREAD

**Issue by beohosting** [The-Network-Crew/CSF-Unblocker-for-WHMCS#2]
Hello,
I cant see module show in client area?

**Comment by beohosting** [comment]
@lsthompson @eerugg Do 

Hello,
I cant see module show in client area?

**Comment by lsthompson** [comment]
Hi, this isn't a proper Issue.

Please detail the steps you've taken.

**Comment by beohosting** [comment]
I downloaded uploded to module/addon i activate it i see it and work in
admin area, but i cant fins i client area where module is showen

**Comment by beohosting** [comment]
@lsthompson do you have scrn where need to be in client area field for unblock, i use whmcs 8.10.1....

<img width="1337" alt="Screenshot 2024-05-18 at 18 03 02" src="https://github.com/The-Network-Crew/CSF-Unblocker-for-WHMCS/assets/169728964/fc734f23-5c82-468c-804c-aceee9c072c1">

I see it in admin no in client area

**Comment by beohosting** [comment]
@lsthompson @eerugg Can you maybe write detailed instruction for this: 

📋 (Module) Permission Requirements

software-ConfigServer-csf (WHM > Reseller ACL > needs this enabled)
whmuser:0:USE,ALLOW,DENY,GREP,UNBLOCK (within /etc/csf/csf.resellers)

**Comment by beohosting** [comment]
@lsthompson I tested in whmcs ADMIN area and its work, i unblock IP, but regular user not reseller cant see field to unblock ? Is this module only for resellers or?

**Comment by lsthompson** [comment]
Client Area. Try this within:

1. In the left-hand menu click on Services, then My Services
2. Go to the Service page for your Hosting account 
3. Browse down the page for the Firewall Unblocking tool
4. This will let you check your IP Address in the Firewall
5. If blocked, it will also advise you of the Block Reason

Re: CSF ACL, I think any provider who runs CSF should be able to understand that, especially if they've read all docs.

**Comment by beohosting** [comment]
@lsthompson Hello Luke, nothing show in client area In the left-hand menu click on Services, then My Services.

I think problem is tmpl file for client area... 
Everthing work in admin, but in client area no option to show for unblock... setup by my side is okey...

**Comment by lsthompson** [comment]
You're not reading properly.

I am close to shutting this.

**Comment by beohosting** [comment]
I do everthing see scrn
<img width="1592" alt="Screenshot 2024-05-19 at 00 33 36" src="https://github.com/The-Network-Crew/CSF-Unblocker-for-WHMCS/assets/169728964/adb6907a-1864-49ea-b388-f6f1e3fa0121">

**Comment by lsthompson** [comment]
Which version of WHMCS Core? 

Which template for Client Area?

**Comment by beohosting** [comment]
whmcs core is 8.10.1.... lagom theme, but i try with hexa too... nothing... only admin work

**Comment by lsthompson** [comment]
OK, try with a stock template?

Also, do you have Smarty enabled?

**Comment by beohosting** [comment]
Allow Smarty PHP Tags is disabled

**Comment by lsthompson** [comment]
Try enabling them.

If no joy, also change theme.

**Comment by beohosting** [comment]
try 21 theme and six nothing... nvm i will find another module thanks

**Comment by lsthompson** [comment]
And that is with Smarty tags enabled?

**Comment by beohosting** [comment]
yes, but i get warning with smarty tags in admin area

**Comment by lsthompson** [comment]
Is it working when you have Smarty tags enabled?

**Comment by lsthompson** [comment]
It's testing working on v8.10.1 via Client Area > Support > Firewall Unblocker.

**Comment by lsthompson** [comment]
No fault verified - changing outcome.

**Comment by beohosting** [comment]
LOL. Yea its on support ... Can you make on some update to be under service ?

**Comment by lsthompson** [comment]
> LOL. Yea its on support ... Can you make on some update to be under service?

It's okay how it is for now. We will review the Smarty side at some stage though.

You said you're changing to another module anyway, so why do you care now?

**Comment by beohosting** [comment]
i think not to bother you... i just give an advice :)

**Comment by lsthompson** [comment]
With how you've requested support overnight into today, no thanks. Glad you're laughing & smiling.

Smarty tags can be disabled, if you do silently continue using the module. It doesn't use SmartyBC.

**Comment by beohosting** [comment]
I will not use it. Dont be arogant i didnt have bad mind. Good night

**Comment by lsthompson** [comment]
If you can't see arrogance and/or blatant lack of info in your OP/replies here, then I'll leave it at that.

I've improved the README to make sure it's clearer for everyone where the GUIs are. :)

Keep in mind these fast replies have been on a weekend. Thank you.

**Comment by beohosting** [comment]
Okey, thanks for fast answers on the weekend. I will keep that on mind. Please understand that i didnt have bad vibes, or bad wishes. Have a good night. And thank you!

**Comment by lsthompson** [comment]
Main thing mate, is that you need to slow down and do more DIY work before you raise support requests.

Your replies were in seconds sometimes. Just as this is Issue #2, no one else was unable to find it, etc.

I think you will find positive support interactions where you give full context/info, and take the time (check, verify, etc).

Of course, you may entirely disagree with the above - the timestamps are all there. I hope you can take it on-board.

I've said nothing of your vibes! You just seem way too excited/young/inexperienced in how you've worked with us.

**Comment by lsthompson** [comment]
I woke up to 4 emails from this Issue - 3 tagged me. Instead, edit your single reply that you had sent.

Show some courtesy (which ties into what I've explained with your rapid-fire responses also).

I hope it helps you. Glad that this has resulted in an improved README. Thank you. :)

**Comment by lsthompson** [comment]
@beohosting 

Wow. 15 hours ago - 4 star review on WHMCS Marketplace:

> Filip Popovic @filip8128
> May 18, 2024 at 01:27:57 PM
> 
> Hello, I cant see unblock field in client area? 

Please change to 5 stars and amend to fixed etc. How rude!

If there are no bad vibes then why would you tarnish open-source software? :(

![Screenshot 2024-05-19 at 3 07 07 PM](https://github.com/The-Network-Crew/CSF-Unblocker-for-WHMCS/assets/73861168/ae52060c-501e-4416-8032-93820918bc9e)

**Comment by lsthompson** [comment]
So @beohosting is abusive of open-source projects. Good to get confirmation, Filip.

Which means what you've said above is an outright lie. Please fix your review if not.
