### ISSUE TITLE
Unblock IP not showing in client area

### ISSUE THREAD

**Issue by infusedhosting** [The-Network-Crew/CSF-Unblocker-for-WHMCS#3]
Can't seem to get the unblock IP function to load in the client area. Works fine on the admin side.

WHMCS Version: 8.10.1

Tried with our current customised theme and the default themes provided with WHMCS.

Thankyou

**Comment by lsthompson** [comment]
Hi there,

Just checking you're looking in the right place? Please take a look at the README.

Thanks!
